# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  application:
    docker:
      - image: circleci/buildpack-deps:18.10

    working_directory: ~/minesweeper

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install pip
          command: |
            sudo apt update
            sudo apt install -y python-pip python-dev

      - run:
          name: Install AWS CLI
          command: pip install awscli

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="19.03.4"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Set Environment Variables
          command: |
            SECRET=$(aws secretsmanager get-secret-value --secret-id minesweeper_db_credentials --region us-east-1 | jq '.SecretString | fromjson')
            echo "export DB_USERNAME=$(echo $SECRET | jq -r '.username')" >> $BASH_ENV
            echo "export DB_PASSWORD=$(echo $SECRET | jq -r '.password')" >> $BASH_ENV
            echo "export DB_URL=$(echo $SECRET | jq -r '.url')" >> $BASH_ENV
            echo "export ECR_REPOSITORY=$(echo $SECRET | jq -r '.repository')" >> $BASH_ENV
            echo "export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)" >> $BASH_ENV

      - run:
          name: Build and Push Docker Image
          command: |
            aws ecr get-login --no-include-email --region us-east-1 | /bin/bash
            docker build --build-arg DB_USERNAME --build-arg DB_PASSWORD --build-arg DB_URL --build-arg VERSION -t minesweeper .
            docker tag minesweeper:latest $ECR_REPOSITORY:$VERSION
            docker push $ECR_REPOSITORY:$VERSION
  infrastructure:
    docker:
      - image: hashicorp/terraform

    working_directory: ~/minesweeper/terraform

    steps:
      - checkout:
          path: ~/minesweeper

      - run:
          name: Terraform Init
          command: |
            echo "export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)" >> $BASH_ENV
            terraform init

      - run:
          name: Terraform Plan
          command: |
            terraform plan -var "image_version=$VERSION" -o plan.tfplan

      - run:
          name: Terraform Apply
          command: |
            ls -la plan.tfplan
            echo $VERSION
            # terraform apply -var "image_version=$VERSION" plan.tfplan
workflows:
  version: 2
  deploy:
    jobs:
      - application
      - infrastructure:
          requires:
            - application
